// flow-typed signature: ff2266c570939af04268c547456ea746
// flow-typed version: <<STUB>>/autonumeric_v1.9.46/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'autonumeric'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'autonumeric' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'autonumeric/autoNumeric-2.0/autoNumeric-2.0-BETA' {
  declare module.exports: any;
}

declare module 'autonumeric/autoNumeric-min' {
  declare module.exports: any;
}

declare module 'autonumeric/autoNumeric' {
  declare module.exports: any;
}

// Filename aliases
declare module 'autonumeric/autoNumeric-2.0/autoNumeric-2.0-BETA.js' {
  declare module.exports: $Exports<'autonumeric/autoNumeric-2.0/autoNumeric-2.0-BETA'>;
}
declare module 'autonumeric/autoNumeric-min.js' {
  declare module.exports: $Exports<'autonumeric/autoNumeric-min'>;
}
declare module 'autonumeric/autoNumeric.js' {
  declare module.exports: $Exports<'autonumeric/autoNumeric'>;
}
