// flow-typed signature: 1b4f3dd3fea55d91eab173909e29b96c
// flow-typed version: <<STUB>>/bootstrap-markdown_v2.10.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-markdown/js/bootstrap-markdown' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.ar' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.cs' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.da' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.de' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.es' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.fa' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.fr' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.ja' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.kr' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.nb' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.nl' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.pl' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.ru' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.sl' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.sv' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.tr' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.ua' {
  declare module.exports: any;
}

declare module 'bootstrap-markdown/locale/bootstrap-markdown.zh' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-markdown/js/bootstrap-markdown.js' {
  declare module.exports: $Exports<'bootstrap-markdown/js/bootstrap-markdown'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.ar.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.ar'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.cs.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.cs'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.da.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.da'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.de.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.de'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.es.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.es'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.fa.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.fa'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.fr.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.fr'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.ja.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.ja'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.kr.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.kr'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.nb.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.nb'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.nl.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.nl'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.pl.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.pl'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.ru.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.ru'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.sl.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.sl'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.sv.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.sv'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.tr.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.tr'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.ua.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.ua'>;
}
declare module 'bootstrap-markdown/locale/bootstrap-markdown.zh.js' {
  declare module.exports: $Exports<'bootstrap-markdown/locale/bootstrap-markdown.zh'>;
}
