// flow-typed signature: c85a51c85a668c9058a3b6739bdbe67d
// flow-typed version: <<STUB>>/chado_v0.2.5/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chado'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chado' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chado/example/example' {
  declare module.exports: any;
}

declare module 'chado/example/mocha_chado' {
  declare module.exports: any;
}

declare module 'chado/Gruntfile' {
  declare module.exports: any;
}

declare module 'chado/lib/actionString' {
  declare module.exports: any;
}

declare module 'chado/lib/analyzer' {
  declare module.exports: any;
}

declare module 'chado/lib/array_combiner' {
  declare module.exports: any;
}

declare module 'chado/lib/array_transformer' {
  declare module.exports: any;
}

declare module 'chado/lib/assume' {
  declare module.exports: any;
}

declare module 'chado/lib/chado' {
  declare module.exports: any;
}

declare module 'chado/lib/compare' {
  declare module.exports: any;
}

declare module 'chado/lib/create_verification' {
  declare module.exports: any;
}

declare module 'chado/lib/find_in_stack' {
  declare module.exports: any;
}

declare module 'chado/lib/reporter/console_reporter' {
  declare module.exports: any;
}

declare module 'chado/lib/save' {
  declare module.exports: any;
}

declare module 'chado/lib/stringify' {
  declare module.exports: any;
}

declare module 'chado/lib/testdouble' {
  declare module.exports: any;
}

declare module 'chado/lib/track' {
  declare module.exports: any;
}

declare module 'chado/lib/types' {
  declare module.exports: any;
}

declare module 'chado/lib/verify' {
  declare module.exports: any;
}

declare module 'chado/test/actionString' {
  declare module.exports: any;
}

declare module 'chado/test/analyzer' {
  declare module.exports: any;
}

declare module 'chado/test/array_combiner' {
  declare module.exports: any;
}

declare module 'chado/test/array_transformer' {
  declare module.exports: any;
}

declare module 'chado/test/assume' {
  declare module.exports: any;
}

declare module 'chado/test/assumeWithRealObject' {
  declare module.exports: any;
}

declare module 'chado/test/chado' {
  declare module.exports: any;
}

declare module 'chado/test/compare' {
  declare module.exports: any;
}

declare module 'chado/test/create_verification' {
  declare module.exports: any;
}

declare module 'chado/test/find_in_stack' {
  declare module.exports: any;
}

declare module 'chado/test/save' {
  declare module.exports: any;
}

declare module 'chado/test/stringify' {
  declare module.exports: any;
}

declare module 'chado/test/testdouble' {
  declare module.exports: any;
}

declare module 'chado/test/track' {
  declare module.exports: any;
}

declare module 'chado/test/verify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chado/example/example.js' {
  declare module.exports: $Exports<'chado/example/example'>;
}
declare module 'chado/example/mocha_chado.js' {
  declare module.exports: $Exports<'chado/example/mocha_chado'>;
}
declare module 'chado/Gruntfile.js' {
  declare module.exports: $Exports<'chado/Gruntfile'>;
}
declare module 'chado/lib/actionString.js' {
  declare module.exports: $Exports<'chado/lib/actionString'>;
}
declare module 'chado/lib/analyzer.js' {
  declare module.exports: $Exports<'chado/lib/analyzer'>;
}
declare module 'chado/lib/array_combiner.js' {
  declare module.exports: $Exports<'chado/lib/array_combiner'>;
}
declare module 'chado/lib/array_transformer.js' {
  declare module.exports: $Exports<'chado/lib/array_transformer'>;
}
declare module 'chado/lib/assume.js' {
  declare module.exports: $Exports<'chado/lib/assume'>;
}
declare module 'chado/lib/chado.js' {
  declare module.exports: $Exports<'chado/lib/chado'>;
}
declare module 'chado/lib/compare.js' {
  declare module.exports: $Exports<'chado/lib/compare'>;
}
declare module 'chado/lib/create_verification.js' {
  declare module.exports: $Exports<'chado/lib/create_verification'>;
}
declare module 'chado/lib/find_in_stack.js' {
  declare module.exports: $Exports<'chado/lib/find_in_stack'>;
}
declare module 'chado/lib/reporter/console_reporter.js' {
  declare module.exports: $Exports<'chado/lib/reporter/console_reporter'>;
}
declare module 'chado/lib/save.js' {
  declare module.exports: $Exports<'chado/lib/save'>;
}
declare module 'chado/lib/stringify.js' {
  declare module.exports: $Exports<'chado/lib/stringify'>;
}
declare module 'chado/lib/testdouble.js' {
  declare module.exports: $Exports<'chado/lib/testdouble'>;
}
declare module 'chado/lib/track.js' {
  declare module.exports: $Exports<'chado/lib/track'>;
}
declare module 'chado/lib/types.js' {
  declare module.exports: $Exports<'chado/lib/types'>;
}
declare module 'chado/lib/verify.js' {
  declare module.exports: $Exports<'chado/lib/verify'>;
}
declare module 'chado/test/actionString.js' {
  declare module.exports: $Exports<'chado/test/actionString'>;
}
declare module 'chado/test/analyzer.js' {
  declare module.exports: $Exports<'chado/test/analyzer'>;
}
declare module 'chado/test/array_combiner.js' {
  declare module.exports: $Exports<'chado/test/array_combiner'>;
}
declare module 'chado/test/array_transformer.js' {
  declare module.exports: $Exports<'chado/test/array_transformer'>;
}
declare module 'chado/test/assume.js' {
  declare module.exports: $Exports<'chado/test/assume'>;
}
declare module 'chado/test/assumeWithRealObject.js' {
  declare module.exports: $Exports<'chado/test/assumeWithRealObject'>;
}
declare module 'chado/test/chado.js' {
  declare module.exports: $Exports<'chado/test/chado'>;
}
declare module 'chado/test/compare.js' {
  declare module.exports: $Exports<'chado/test/compare'>;
}
declare module 'chado/test/create_verification.js' {
  declare module.exports: $Exports<'chado/test/create_verification'>;
}
declare module 'chado/test/find_in_stack.js' {
  declare module.exports: $Exports<'chado/test/find_in_stack'>;
}
declare module 'chado/test/save.js' {
  declare module.exports: $Exports<'chado/test/save'>;
}
declare module 'chado/test/stringify.js' {
  declare module.exports: $Exports<'chado/test/stringify'>;
}
declare module 'chado/test/testdouble.js' {
  declare module.exports: $Exports<'chado/test/testdouble'>;
}
declare module 'chado/test/track.js' {
  declare module.exports: $Exports<'chado/test/track'>;
}
declare module 'chado/test/verify.js' {
  declare module.exports: $Exports<'chado/test/verify'>;
}
