// flow-typed signature: 0e9d2c6611fd5e6ef972fbfa679e8272
// flow-typed version: <<STUB>>/CoolBeans_v0.0.9/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'CoolBeans'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'CoolBeans' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'CoolBeans/lib/CoolBeans' {
  declare module.exports: any;
}

// Filename aliases
declare module 'CoolBeans/index' {
  declare module.exports: $Exports<'CoolBeans'>;
}
declare module 'CoolBeans/index.js' {
  declare module.exports: $Exports<'CoolBeans'>;
}
declare module 'CoolBeans/lib/CoolBeans.js' {
  declare module.exports: $Exports<'CoolBeans/lib/CoolBeans'>;
}
