// flow-typed signature: e6aef7ef15a7b56f44859348abe4bf64
// flow-typed version: <<STUB>>/datatables.net-bs_v1.10.12/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'datatables.net-bs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'datatables.net-bs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'datatables.net-bs/js/dataTables.bootstrap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'datatables.net-bs/js/dataTables.bootstrap.js' {
  declare module.exports: $Exports<'datatables.net-bs/js/dataTables.bootstrap'>;
}
