// flow-typed signature: deabcc40be111ad36c473d42c59f04e0
// flow-typed version: <<STUB>>/drmonty-smartmenus_v0.9.7/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'drmonty-smartmenus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'drmonty-smartmenus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'drmonty-smartmenus/js/jquery.smartmenus.bootstrap' {
  declare module.exports: any;
}

declare module 'drmonty-smartmenus/js/jquery.smartmenus.bootstrap.min' {
  declare module.exports: any;
}

declare module 'drmonty-smartmenus/js/jquery.smartmenus' {
  declare module.exports: any;
}

declare module 'drmonty-smartmenus/js/jquery.smartmenus.keyboard' {
  declare module.exports: any;
}

declare module 'drmonty-smartmenus/js/jquery.smartmenus.keyboard.min' {
  declare module.exports: any;
}

declare module 'drmonty-smartmenus/js/jquery.smartmenus.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'drmonty-smartmenus/js/jquery.smartmenus.bootstrap.js' {
  declare module.exports: $Exports<'drmonty-smartmenus/js/jquery.smartmenus.bootstrap'>;
}
declare module 'drmonty-smartmenus/js/jquery.smartmenus.bootstrap.min.js' {
  declare module.exports: $Exports<'drmonty-smartmenus/js/jquery.smartmenus.bootstrap.min'>;
}
declare module 'drmonty-smartmenus/js/jquery.smartmenus.js' {
  declare module.exports: $Exports<'drmonty-smartmenus/js/jquery.smartmenus'>;
}
declare module 'drmonty-smartmenus/js/jquery.smartmenus.keyboard.js' {
  declare module.exports: $Exports<'drmonty-smartmenus/js/jquery.smartmenus.keyboard'>;
}
declare module 'drmonty-smartmenus/js/jquery.smartmenus.keyboard.min.js' {
  declare module.exports: $Exports<'drmonty-smartmenus/js/jquery.smartmenus.keyboard.min'>;
}
declare module 'drmonty-smartmenus/js/jquery.smartmenus.min.js' {
  declare module.exports: $Exports<'drmonty-smartmenus/js/jquery.smartmenus.min'>;
}
