// flow-typed signature: 9ad2cfdb504b0b3b98401b7dffb7db8b
// flow-typed version: <<STUB>>/ezmlm-node_v1.2.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ezmlm-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ezmlm-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ezmlm-node/lib/ezmlmExec' {
  declare module.exports: any;
}

declare module 'ezmlm-node/lib/flags' {
  declare module.exports: any;
}

declare module 'ezmlm-node/lib/index' {
  declare module.exports: any;
}

declare module 'ezmlm-node/lib/modifyHeaders' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ezmlm-node/lib/ezmlmExec.js' {
  declare module.exports: $Exports<'ezmlm-node/lib/ezmlmExec'>;
}
declare module 'ezmlm-node/lib/flags.js' {
  declare module.exports: $Exports<'ezmlm-node/lib/flags'>;
}
declare module 'ezmlm-node/lib/index.js' {
  declare module.exports: $Exports<'ezmlm-node/lib/index'>;
}
declare module 'ezmlm-node/lib/modifyHeaders.js' {
  declare module.exports: $Exports<'ezmlm-node/lib/modifyHeaders'>;
}
