// flow-typed signature: 7d741b18b4a7ad2480322958aa0326b9
// flow-typed version: <<STUB>>/grunt-mocha-istanbul_v5.0.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-mocha-istanbul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-mocha-istanbul' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-mocha-istanbul/es6/file.es6' {
  declare module.exports: any;
}

declare module 'grunt-mocha-istanbul/Gruntfile' {
  declare module.exports: any;
}

declare module 'grunt-mocha-istanbul/lib/src/other' {
  declare module.exports: any;
}

declare module 'grunt-mocha-istanbul/lib/src/some' {
  declare module.exports: any;
}

declare module 'grunt-mocha-istanbul/tasks/index' {
  declare module.exports: any;
}

declare module 'grunt-mocha-istanbul/test/dummy.test' {
  declare module.exports: any;
}

declare module 'grunt-mocha-istanbul/test/excluded1' {
  declare module.exports: any;
}

declare module 'grunt-mocha-istanbul/test/ignored_file.test' {
  declare module.exports: any;
}

declare module 'grunt-mocha-istanbul/test/test.es5' {
  declare module.exports: any;
}

declare module 'grunt-mocha-istanbul/test/test.es6' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-mocha-istanbul/es6/file.es6.js' {
  declare module.exports: $Exports<'grunt-mocha-istanbul/es6/file.es6'>;
}
declare module 'grunt-mocha-istanbul/Gruntfile.js' {
  declare module.exports: $Exports<'grunt-mocha-istanbul/Gruntfile'>;
}
declare module 'grunt-mocha-istanbul/lib/src/other.js' {
  declare module.exports: $Exports<'grunt-mocha-istanbul/lib/src/other'>;
}
declare module 'grunt-mocha-istanbul/lib/src/some.js' {
  declare module.exports: $Exports<'grunt-mocha-istanbul/lib/src/some'>;
}
declare module 'grunt-mocha-istanbul/tasks/index.js' {
  declare module.exports: $Exports<'grunt-mocha-istanbul/tasks/index'>;
}
declare module 'grunt-mocha-istanbul/test/dummy.test.js' {
  declare module.exports: $Exports<'grunt-mocha-istanbul/test/dummy.test'>;
}
declare module 'grunt-mocha-istanbul/test/excluded1.js' {
  declare module.exports: $Exports<'grunt-mocha-istanbul/test/excluded1'>;
}
declare module 'grunt-mocha-istanbul/test/ignored_file.test.js' {
  declare module.exports: $Exports<'grunt-mocha-istanbul/test/ignored_file.test'>;
}
declare module 'grunt-mocha-istanbul/test/test.es5.js' {
  declare module.exports: $Exports<'grunt-mocha-istanbul/test/test.es5'>;
}
declare module 'grunt-mocha-istanbul/test/test.es6.js' {
  declare module.exports: $Exports<'grunt-mocha-istanbul/test/test.es6'>;
}
