// flow-typed signature: 382328692ec60ca1e7715fbfda66634a
// flow-typed version: <<STUB>>/grunt-contrib-pug_v1.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-contrib-pug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-contrib-pug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-contrib-pug/tasks/lib/pug' {
  declare module.exports: any;
}

declare module 'grunt-contrib-pug/tasks/pug' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-contrib-pug/tasks/lib/pug.js' {
  declare module.exports: $Exports<'grunt-contrib-pug/tasks/lib/pug'>;
}
declare module 'grunt-contrib-pug/tasks/pug.js' {
  declare module.exports: $Exports<'grunt-contrib-pug/tasks/pug'>;
}
