// flow-typed signature: 534d86a08c4722fea69bbc105cf88a54
// flow-typed version: <<STUB>>/grunt-contrib-uglify_v2.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-contrib-uglify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-contrib-uglify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-contrib-uglify/tasks/lib/uglify' {
  declare module.exports: any;
}

declare module 'grunt-contrib-uglify/tasks/uglify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-contrib-uglify/tasks/lib/uglify.js' {
  declare module.exports: $Exports<'grunt-contrib-uglify/tasks/lib/uglify'>;
}
declare module 'grunt-contrib-uglify/tasks/uglify.js' {
  declare module.exports: $Exports<'grunt-contrib-uglify/tasks/uglify'>;
}
