// flow-typed signature: 1807b5114cc5b42c3ab17de96ded70bb
// flow-typed version: <<STUB>>/grunt-eslint_v19.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-eslint/tasks/eslint' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-eslint/tasks/eslint.js' {
  declare module.exports: $Exports<'grunt-eslint/tasks/eslint'>;
}
