// flow-typed signature: 3c77853760c10c9cd6d61b3b930932da
// flow-typed version: <<STUB>>/grunt-cli_v1.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-cli/lib/cli' {
  declare module.exports: any;
}

declare module 'grunt-cli/lib/completion' {
  declare module.exports: any;
}

declare module 'grunt-cli/lib/info' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-cli/lib/cli.js' {
  declare module.exports: $Exports<'grunt-cli/lib/cli'>;
}
declare module 'grunt-cli/lib/completion.js' {
  declare module.exports: $Exports<'grunt-cli/lib/completion'>;
}
declare module 'grunt-cli/lib/info.js' {
  declare module.exports: $Exports<'grunt-cli/lib/info'>;
}
