// flow-typed signature: 71c466c420da3e7ab602308f09b6b01f
// flow-typed version: <<STUB>>/grunt-karma_v2.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-karma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-karma' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-karma/gruntfile' {
  declare module.exports: any;
}

declare module 'grunt-karma/karma.conf' {
  declare module.exports: any;
}

declare module 'grunt-karma/lib/background' {
  declare module.exports: any;
}

declare module 'grunt-karma/tasks/grunt-karma' {
  declare module.exports: any;
}

declare module 'grunt-karma/test/grunt-karma-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-karma/gruntfile.js' {
  declare module.exports: $Exports<'grunt-karma/gruntfile'>;
}
declare module 'grunt-karma/karma.conf.js' {
  declare module.exports: $Exports<'grunt-karma/karma.conf'>;
}
declare module 'grunt-karma/lib/background.js' {
  declare module.exports: $Exports<'grunt-karma/lib/background'>;
}
declare module 'grunt-karma/tasks/grunt-karma.js' {
  declare module.exports: $Exports<'grunt-karma/tasks/grunt-karma'>;
}
declare module 'grunt-karma/test/grunt-karma-test.js' {
  declare module.exports: $Exports<'grunt-karma/test/grunt-karma-test'>;
}
