// flow-typed signature: 3675bf666376e7565bca0f5d0cc64632
// flow-typed version: <<STUB>>/grunt-contrib-less_v1.4.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-contrib-less'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-contrib-less' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-contrib-less/tasks/less' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-contrib-less/tasks/less.js' {
  declare module.exports: $Exports<'grunt-contrib-less/tasks/less'>;
}
