// flow-typed signature: 6d2bc2aac5c696f97616ddce2282424d
// flow-typed version: <<STUB>>/grunt-puglint_v1.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-puglint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-puglint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-puglint/lib/formatter' {
  declare module.exports: any;
}

declare module 'grunt-puglint/tasks/puglint' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-puglint/lib/formatter.js' {
  declare module.exports: $Exports<'grunt-puglint/lib/formatter'>;
}
declare module 'grunt-puglint/tasks/puglint.js' {
  declare module.exports: $Exports<'grunt-puglint/tasks/puglint'>;
}
