// flow-typed signature: fbca7d6823c98e0743572285c702b1fa
// flow-typed version: <<STUB>>/grunt-patcher_v1.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-patcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-patcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-patcher/Gruntfile' {
  declare module.exports: any;
}

declare module 'grunt-patcher/tasks/patch' {
  declare module.exports: any;
}

declare module 'grunt-patcher/test/patch_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-patcher/Gruntfile.js' {
  declare module.exports: $Exports<'grunt-patcher/Gruntfile'>;
}
declare module 'grunt-patcher/tasks/patch.js' {
  declare module.exports: $Exports<'grunt-patcher/tasks/patch'>;
}
declare module 'grunt-patcher/test/patch_test.js' {
  declare module.exports: $Exports<'grunt-patcher/test/patch_test'>;
}
