// flow-typed signature: 1eb0ac44bff661b4634c0c19786f6387
// flow-typed version: <<STUB>>/guillotine_v1.3.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'guillotine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'guillotine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'guillotine/js/jquery.guillotine' {
  declare module.exports: any;
}

declare module 'guillotine/js/jquery.guillotine.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'guillotine/js/jquery.guillotine.js' {
  declare module.exports: $Exports<'guillotine/js/jquery.guillotine'>;
}
declare module 'guillotine/js/jquery.guillotine.min.js' {
  declare module.exports: $Exports<'guillotine/js/jquery.guillotine.min'>;
}
