// flow-typed signature: e620594d4eaa5d5b9daa5e41162226ca
// flow-typed version: <<STUB>>/i18next-intervalplural-postprocessor_v1.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-intervalplural-postprocessor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-intervalplural-postprocessor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18next-intervalplural-postprocessor/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'i18next-intervalplural-postprocessor/dist/es/index' {
  declare module.exports: any;
}

declare module 'i18next-intervalplural-postprocessor/dist/umd/i18nextIntervalPluralPostProcessor' {
  declare module.exports: any;
}

declare module 'i18next-intervalplural-postprocessor/dist/umd/i18nextIntervalPluralPostProcessor.min' {
  declare module.exports: any;
}

declare module 'i18next-intervalplural-postprocessor/i18nextIntervalPluralPostProcessor' {
  declare module.exports: any;
}

declare module 'i18next-intervalplural-postprocessor/i18nextIntervalPluralPostProcessor.min' {
  declare module.exports: any;
}

declare module 'i18next-intervalplural-postprocessor/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18next-intervalplural-postprocessor/dist/commonjs/index.js' {
  declare module.exports: $Exports<'i18next-intervalplural-postprocessor/dist/commonjs/index'>;
}
declare module 'i18next-intervalplural-postprocessor/dist/es/index.js' {
  declare module.exports: $Exports<'i18next-intervalplural-postprocessor/dist/es/index'>;
}
declare module 'i18next-intervalplural-postprocessor/dist/umd/i18nextIntervalPluralPostProcessor.js' {
  declare module.exports: $Exports<'i18next-intervalplural-postprocessor/dist/umd/i18nextIntervalPluralPostProcessor'>;
}
declare module 'i18next-intervalplural-postprocessor/dist/umd/i18nextIntervalPluralPostProcessor.min.js' {
  declare module.exports: $Exports<'i18next-intervalplural-postprocessor/dist/umd/i18nextIntervalPluralPostProcessor.min'>;
}
declare module 'i18next-intervalplural-postprocessor/i18nextIntervalPluralPostProcessor.js' {
  declare module.exports: $Exports<'i18next-intervalplural-postprocessor/i18nextIntervalPluralPostProcessor'>;
}
declare module 'i18next-intervalplural-postprocessor/i18nextIntervalPluralPostProcessor.min.js' {
  declare module.exports: $Exports<'i18next-intervalplural-postprocessor/i18nextIntervalPluralPostProcessor.min'>;
}
declare module 'i18next-intervalplural-postprocessor/index' {
  declare module.exports: $Exports<'i18next-intervalplural-postprocessor'>;
}
declare module 'i18next-intervalplural-postprocessor/index.js' {
  declare module.exports: $Exports<'i18next-intervalplural-postprocessor'>;
}
declare module 'i18next-intervalplural-postprocessor/rollup.config.js' {
  declare module.exports: $Exports<'i18next-intervalplural-postprocessor/rollup.config'>;
}
