// flow-typed signature: 971e1d2273c42c4be0ee71d75698f0f6
// flow-typed version: <<STUB>>/jqcloud2_v2.0.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jqcloud2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jqcloud2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jqcloud2/dist/jqcloud' {
  declare module.exports: any;
}

declare module 'jqcloud2/dist/jqcloud.min' {
  declare module.exports: any;
}

declare module 'jqcloud2/Gruntfile' {
  declare module.exports: any;
}

declare module 'jqcloud2/src/jqcloud' {
  declare module.exports: any;
}

declare module 'jqcloud2/test/core_tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jqcloud2/dist/jqcloud.js' {
  declare module.exports: $Exports<'jqcloud2/dist/jqcloud'>;
}
declare module 'jqcloud2/dist/jqcloud.min.js' {
  declare module.exports: $Exports<'jqcloud2/dist/jqcloud.min'>;
}
declare module 'jqcloud2/Gruntfile.js' {
  declare module.exports: $Exports<'jqcloud2/Gruntfile'>;
}
declare module 'jqcloud2/src/jqcloud.js' {
  declare module.exports: $Exports<'jqcloud2/src/jqcloud'>;
}
declare module 'jqcloud2/test/core_tests.js' {
  declare module.exports: $Exports<'jqcloud2/test/core_tests'>;
}
