// flow-typed signature: 16642ca1b7643c1f88a79e179c9a1c1c
// flow-typed version: <<STUB>>/jquery-validation_v1.15.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery-validation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery-validation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery-validation/dist/additional-methods' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/jquery.validate' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_ar' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_bg' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_bn_BD' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_ca' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_cs' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_da' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_de' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_el' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_es_AR' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_es_PE' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_es' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_et' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_eu' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_fa' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_fi' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_fr' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_ge' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_gl' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_he' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_hr' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_hu' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_hy_AM' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_id' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_is' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_it' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_ja' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_ka' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_kk' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_ko' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_lt' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_lv' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_mk' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_my' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_nl' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_no' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_pl' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_pt_BR' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_pt_PT' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_ro' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_ru' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_si' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_sk' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_sl' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_sr_lat' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_sr' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_sv' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_th' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_tj' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_tr' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_uk' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_vi' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_zh_TW' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/messages_zh' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/methods_de' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/methods_es_CL' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/methods_fi' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/methods_nl' {
  declare module.exports: any;
}

declare module 'jquery-validation/dist/localization/methods_pt' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery-validation/dist/additional-methods.js' {
  declare module.exports: $Exports<'jquery-validation/dist/additional-methods'>;
}
declare module 'jquery-validation/dist/jquery.validate.js' {
  declare module.exports: $Exports<'jquery-validation/dist/jquery.validate'>;
}
declare module 'jquery-validation/dist/localization/messages_ar.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_ar'>;
}
declare module 'jquery-validation/dist/localization/messages_bg.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_bg'>;
}
declare module 'jquery-validation/dist/localization/messages_bn_BD.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_bn_BD'>;
}
declare module 'jquery-validation/dist/localization/messages_ca.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_ca'>;
}
declare module 'jquery-validation/dist/localization/messages_cs.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_cs'>;
}
declare module 'jquery-validation/dist/localization/messages_da.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_da'>;
}
declare module 'jquery-validation/dist/localization/messages_de.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_de'>;
}
declare module 'jquery-validation/dist/localization/messages_el.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_el'>;
}
declare module 'jquery-validation/dist/localization/messages_es_AR.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_es_AR'>;
}
declare module 'jquery-validation/dist/localization/messages_es_PE.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_es_PE'>;
}
declare module 'jquery-validation/dist/localization/messages_es.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_es'>;
}
declare module 'jquery-validation/dist/localization/messages_et.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_et'>;
}
declare module 'jquery-validation/dist/localization/messages_eu.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_eu'>;
}
declare module 'jquery-validation/dist/localization/messages_fa.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_fa'>;
}
declare module 'jquery-validation/dist/localization/messages_fi.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_fi'>;
}
declare module 'jquery-validation/dist/localization/messages_fr.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_fr'>;
}
declare module 'jquery-validation/dist/localization/messages_ge.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_ge'>;
}
declare module 'jquery-validation/dist/localization/messages_gl.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_gl'>;
}
declare module 'jquery-validation/dist/localization/messages_he.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_he'>;
}
declare module 'jquery-validation/dist/localization/messages_hr.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_hr'>;
}
declare module 'jquery-validation/dist/localization/messages_hu.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_hu'>;
}
declare module 'jquery-validation/dist/localization/messages_hy_AM.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_hy_AM'>;
}
declare module 'jquery-validation/dist/localization/messages_id.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_id'>;
}
declare module 'jquery-validation/dist/localization/messages_is.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_is'>;
}
declare module 'jquery-validation/dist/localization/messages_it.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_it'>;
}
declare module 'jquery-validation/dist/localization/messages_ja.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_ja'>;
}
declare module 'jquery-validation/dist/localization/messages_ka.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_ka'>;
}
declare module 'jquery-validation/dist/localization/messages_kk.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_kk'>;
}
declare module 'jquery-validation/dist/localization/messages_ko.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_ko'>;
}
declare module 'jquery-validation/dist/localization/messages_lt.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_lt'>;
}
declare module 'jquery-validation/dist/localization/messages_lv.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_lv'>;
}
declare module 'jquery-validation/dist/localization/messages_mk.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_mk'>;
}
declare module 'jquery-validation/dist/localization/messages_my.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_my'>;
}
declare module 'jquery-validation/dist/localization/messages_nl.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_nl'>;
}
declare module 'jquery-validation/dist/localization/messages_no.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_no'>;
}
declare module 'jquery-validation/dist/localization/messages_pl.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_pl'>;
}
declare module 'jquery-validation/dist/localization/messages_pt_BR.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_pt_BR'>;
}
declare module 'jquery-validation/dist/localization/messages_pt_PT.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_pt_PT'>;
}
declare module 'jquery-validation/dist/localization/messages_ro.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_ro'>;
}
declare module 'jquery-validation/dist/localization/messages_ru.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_ru'>;
}
declare module 'jquery-validation/dist/localization/messages_si.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_si'>;
}
declare module 'jquery-validation/dist/localization/messages_sk.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_sk'>;
}
declare module 'jquery-validation/dist/localization/messages_sl.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_sl'>;
}
declare module 'jquery-validation/dist/localization/messages_sr_lat.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_sr_lat'>;
}
declare module 'jquery-validation/dist/localization/messages_sr.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_sr'>;
}
declare module 'jquery-validation/dist/localization/messages_sv.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_sv'>;
}
declare module 'jquery-validation/dist/localization/messages_th.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_th'>;
}
declare module 'jquery-validation/dist/localization/messages_tj.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_tj'>;
}
declare module 'jquery-validation/dist/localization/messages_tr.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_tr'>;
}
declare module 'jquery-validation/dist/localization/messages_uk.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_uk'>;
}
declare module 'jquery-validation/dist/localization/messages_vi.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_vi'>;
}
declare module 'jquery-validation/dist/localization/messages_zh_TW.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_zh_TW'>;
}
declare module 'jquery-validation/dist/localization/messages_zh.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/messages_zh'>;
}
declare module 'jquery-validation/dist/localization/methods_de.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/methods_de'>;
}
declare module 'jquery-validation/dist/localization/methods_es_CL.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/methods_es_CL'>;
}
declare module 'jquery-validation/dist/localization/methods_fi.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/methods_fi'>;
}
declare module 'jquery-validation/dist/localization/methods_nl.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/methods_nl'>;
}
declare module 'jquery-validation/dist/localization/methods_pt.js' {
  declare module.exports: $Exports<'jquery-validation/dist/localization/methods_pt'>;
}
