// flow-typed signature: 0b0dfa0f99b7e9501393dcebdb756b70
// flow-typed version: <<STUB>>/karma-must_v0.1.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-must'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-must' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-must/adapter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-must/adapter.js' {
  declare module.exports: $Exports<'karma-must/adapter'>;
}
declare module 'karma-must/index' {
  declare module.exports: $Exports<'karma-must'>;
}
declare module 'karma-must/index.js' {
  declare module.exports: $Exports<'karma-must'>;
}
