// flow-typed signature: f179378029f86dbf50b682fc7a4f6d5c
// flow-typed version: <<STUB>>/karma-html2js-preprocessor_v1.1.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-html2js-preprocessor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-html2js-preprocessor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-html2js-preprocessor/lib/html2js' {
  declare module.exports: any;
}

declare module 'karma-html2js-preprocessor/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-html2js-preprocessor/lib/html2js.js' {
  declare module.exports: $Exports<'karma-html2js-preprocessor/lib/html2js'>;
}
declare module 'karma-html2js-preprocessor/lib/index.js' {
  declare module.exports: $Exports<'karma-html2js-preprocessor/lib/index'>;
}
