// flow-typed signature: 7e0165de9127ea02e9f6747a462d6d88
// flow-typed version: <<STUB>>/karma-sinon_v1.0.5/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-sinon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-sinon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'karma-sinon/index' {
  declare module.exports: $Exports<'karma-sinon'>;
}
declare module 'karma-sinon/index.js' {
  declare module.exports: $Exports<'karma-sinon'>;
}
