// flow-typed signature: f78f80b6839a9eb061c190384c86b4c5
// flow-typed version: <<STUB>>/less-plugin-clean-css_v1.5.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'less-plugin-clean-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'less-plugin-clean-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'less-plugin-clean-css/lib/clean-css-processor' {
  declare module.exports: any;
}

declare module 'less-plugin-clean-css/lib/index' {
  declare module.exports: any;
}

declare module 'less-plugin-clean-css/lib/parse-options' {
  declare module.exports: any;
}

declare module 'less-plugin-clean-css/lib/usage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'less-plugin-clean-css/lib/clean-css-processor.js' {
  declare module.exports: $Exports<'less-plugin-clean-css/lib/clean-css-processor'>;
}
declare module 'less-plugin-clean-css/lib/index.js' {
  declare module.exports: $Exports<'less-plugin-clean-css/lib/index'>;
}
declare module 'less-plugin-clean-css/lib/parse-options.js' {
  declare module.exports: $Exports<'less-plugin-clean-css/lib/parse-options'>;
}
declare module 'less-plugin-clean-css/lib/usage.js' {
  declare module.exports: $Exports<'less-plugin-clean-css/lib/usage'>;
}
