// flow-typed signature: b102694d232c4ac1049db515d3d4314a
// flow-typed version: <<STUB>>/must-dist_v0.12.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'must-dist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'must-dist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'must-dist/dist/js-must' {
  declare module.exports: any;
}

declare module 'must-dist/lib/assertion_error' {
  declare module.exports: any;
}

declare module 'must-dist/lib/assertions' {
  declare module.exports: any;
}

declare module 'must-dist/lib/exporter' {
  declare module.exports: any;
}

declare module 'must-dist/lib/inspect' {
  declare module.exports: any;
}

declare module 'must-dist/test/assertion_error_test' {
  declare module.exports: any;
}

declare module 'must-dist/test/assertions_test' {
  declare module.exports: any;
}

declare module 'must-dist/test/index_test' {
  declare module.exports: any;
}

declare module 'must-dist/test/inspect_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'must-dist/dist/js-must.js' {
  declare module.exports: $Exports<'must-dist/dist/js-must'>;
}
declare module 'must-dist/index' {
  declare module.exports: $Exports<'must-dist'>;
}
declare module 'must-dist/index.js' {
  declare module.exports: $Exports<'must-dist'>;
}
declare module 'must-dist/lib/assertion_error.js' {
  declare module.exports: $Exports<'must-dist/lib/assertion_error'>;
}
declare module 'must-dist/lib/assertions.js' {
  declare module.exports: $Exports<'must-dist/lib/assertions'>;
}
declare module 'must-dist/lib/exporter.js' {
  declare module.exports: $Exports<'must-dist/lib/exporter'>;
}
declare module 'must-dist/lib/inspect.js' {
  declare module.exports: $Exports<'must-dist/lib/inspect'>;
}
declare module 'must-dist/test/assertion_error_test.js' {
  declare module.exports: $Exports<'must-dist/test/assertion_error_test'>;
}
declare module 'must-dist/test/assertions_test.js' {
  declare module.exports: $Exports<'must-dist/test/assertions_test'>;
}
declare module 'must-dist/test/index_test.js' {
  declare module.exports: $Exports<'must-dist/test/index_test'>;
}
declare module 'must-dist/test/inspect_test.js' {
  declare module.exports: $Exports<'must-dist/test/inspect_test'>;
}
