// flow-typed signature: fc5b77755fe27465d663aaa74231f02a
// flow-typed version: <<STUB>>/node-syntaxhighlighter_v0.8.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-syntaxhighlighter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-syntaxhighlighter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-syntaxhighlighter/examples/highlightself' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/examples/inline-scripts/pageofself-inlineas' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/examples/inline-scripts/pageofself-inlinejs' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/examples/inline-scripts/pageofself-inlinephp' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/examples/pageofself' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/examples/shorthighlight' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/inline-scripts' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shAutoloader' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushAppleScript' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushAS3' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushBash' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushColdFusion' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushCpp' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushCSharp' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushCss' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushDelphi' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushDiff' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushErlang' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushGroovy' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushJava' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushJavaFX' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushJScript' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushPerl' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushPhp' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushPlain' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushPowerShell' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushPython' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushRuby' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushSass' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushScala' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushSql' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushVb' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shBrushXml' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shCore' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/shLegacy' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/lib/scripts/XRegExp' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/node-syntaxhighlighter' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/scripts/nodify' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/test/inlinescripts' {
  declare module.exports: any;
}

declare module 'node-syntaxhighlighter/test/node-syntaxhighlighter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-syntaxhighlighter/examples/highlightself.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/examples/highlightself'>;
}
declare module 'node-syntaxhighlighter/examples/inline-scripts/pageofself-inlineas.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/examples/inline-scripts/pageofself-inlineas'>;
}
declare module 'node-syntaxhighlighter/examples/inline-scripts/pageofself-inlinejs.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/examples/inline-scripts/pageofself-inlinejs'>;
}
declare module 'node-syntaxhighlighter/examples/inline-scripts/pageofself-inlinephp.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/examples/inline-scripts/pageofself-inlinephp'>;
}
declare module 'node-syntaxhighlighter/examples/pageofself.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/examples/pageofself'>;
}
declare module 'node-syntaxhighlighter/examples/shorthighlight.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/examples/shorthighlight'>;
}
declare module 'node-syntaxhighlighter/inline-scripts.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/inline-scripts'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shAutoloader.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shAutoloader'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushAppleScript.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushAppleScript'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushAS3.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushAS3'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushBash.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushBash'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushColdFusion.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushColdFusion'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushCpp.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushCpp'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushCSharp.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushCSharp'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushCss.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushCss'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushDelphi.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushDelphi'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushDiff.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushDiff'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushErlang.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushErlang'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushGroovy.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushGroovy'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushJava.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushJava'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushJavaFX.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushJavaFX'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushJScript.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushJScript'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushPerl.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushPerl'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushPhp.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushPhp'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushPlain.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushPlain'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushPowerShell.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushPowerShell'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushPython.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushPython'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushRuby.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushRuby'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushSass.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushSass'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushScala.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushScala'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushSql.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushSql'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushVb.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushVb'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shBrushXml.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shBrushXml'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shCore.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shCore'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/shLegacy.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/shLegacy'>;
}
declare module 'node-syntaxhighlighter/lib/scripts/XRegExp.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/lib/scripts/XRegExp'>;
}
declare module 'node-syntaxhighlighter/node-syntaxhighlighter.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/node-syntaxhighlighter'>;
}
declare module 'node-syntaxhighlighter/scripts/nodify.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/scripts/nodify'>;
}
declare module 'node-syntaxhighlighter/test/inlinescripts.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/test/inlinescripts'>;
}
declare module 'node-syntaxhighlighter/test/node-syntaxhighlighter.js' {
  declare module.exports: $Exports<'node-syntaxhighlighter/test/node-syntaxhighlighter'>;
}
