// flow-typed signature: 89b32001a0a0b09edf97aeebb09bdf5b
// flow-typed version: <<STUB>>/node-html-encoder_v0.0.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-html-encoder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-html-encoder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-html-encoder/lib/encoder' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-html-encoder/lib/encoder.js' {
  declare module.exports: $Exports<'node-html-encoder/lib/encoder'>;
}
