// flow-typed signature: c8484bd68aa5d305a4ae9749c8a62c2f
// flow-typed version: <<STUB>>/openidconnect-for-passport_v0.0.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'openidconnect-for-passport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'openidconnect-for-passport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'openidconnect-for-passport/lib/configuration' {
  declare module.exports: any;
}

declare module 'openidconnect-for-passport/lib/debug_log' {
  declare module.exports: any;
}

declare module 'openidconnect-for-passport/lib/discovery/lrdd' {
  declare module.exports: any;
}

declare module 'openidconnect-for-passport/lib/discovery/webfinger' {
  declare module.exports: any;
}

declare module 'openidconnect-for-passport/lib/errors/internaloautherror' {
  declare module.exports: any;
}

declare module 'openidconnect-for-passport/lib/index' {
  declare module.exports: any;
}

declare module 'openidconnect-for-passport/lib/registration' {
  declare module.exports: any;
}

declare module 'openidconnect-for-passport/lib/setup' {
  declare module.exports: any;
}

declare module 'openidconnect-for-passport/lib/strategy' {
  declare module.exports: any;
}

declare module 'openidconnect-for-passport/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'openidconnect-for-passport/lib/configuration.js' {
  declare module.exports: $Exports<'openidconnect-for-passport/lib/configuration'>;
}
declare module 'openidconnect-for-passport/lib/debug_log.js' {
  declare module.exports: $Exports<'openidconnect-for-passport/lib/debug_log'>;
}
declare module 'openidconnect-for-passport/lib/discovery/lrdd.js' {
  declare module.exports: $Exports<'openidconnect-for-passport/lib/discovery/lrdd'>;
}
declare module 'openidconnect-for-passport/lib/discovery/webfinger.js' {
  declare module.exports: $Exports<'openidconnect-for-passport/lib/discovery/webfinger'>;
}
declare module 'openidconnect-for-passport/lib/errors/internaloautherror.js' {
  declare module.exports: $Exports<'openidconnect-for-passport/lib/errors/internaloautherror'>;
}
declare module 'openidconnect-for-passport/lib/index.js' {
  declare module.exports: $Exports<'openidconnect-for-passport/lib/index'>;
}
declare module 'openidconnect-for-passport/lib/registration.js' {
  declare module.exports: $Exports<'openidconnect-for-passport/lib/registration'>;
}
declare module 'openidconnect-for-passport/lib/setup.js' {
  declare module.exports: $Exports<'openidconnect-for-passport/lib/setup'>;
}
declare module 'openidconnect-for-passport/lib/strategy.js' {
  declare module.exports: $Exports<'openidconnect-for-passport/lib/strategy'>;
}
declare module 'openidconnect-for-passport/lib/utils.js' {
  declare module.exports: $Exports<'openidconnect-for-passport/lib/utils'>;
}
