// flow-typed signature: 1d5dd462a7873907802aca93db86895f
// flow-typed version: <<STUB>>/passport-openid_v0.4.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-openid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-openid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-openid/lib/passport-openid/errors/badrequesterror' {
  declare module.exports: any;
}

declare module 'passport-openid/lib/passport-openid/errors/internalopeniderror' {
  declare module.exports: any;
}

declare module 'passport-openid/lib/passport-openid/index' {
  declare module.exports: any;
}

declare module 'passport-openid/lib/passport-openid/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-openid/lib/passport-openid/errors/badrequesterror.js' {
  declare module.exports: $Exports<'passport-openid/lib/passport-openid/errors/badrequesterror'>;
}
declare module 'passport-openid/lib/passport-openid/errors/internalopeniderror.js' {
  declare module.exports: $Exports<'passport-openid/lib/passport-openid/errors/internalopeniderror'>;
}
declare module 'passport-openid/lib/passport-openid/index.js' {
  declare module.exports: $Exports<'passport-openid/lib/passport-openid/index'>;
}
declare module 'passport-openid/lib/passport-openid/strategy.js' {
  declare module.exports: $Exports<'passport-openid/lib/passport-openid/strategy'>;
}
