// flow-typed signature: e0dd65445cd6de7cc8fb2de911cfe088
// flow-typed version: <<STUB>>/simple-timepicker_v1.1.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-timepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-timepicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simple-timepicker/dist/simple-timepicker' {
  declare module.exports: any;
}

declare module 'simple-timepicker/dist/simple-timepicker.min' {
  declare module.exports: any;
}

declare module 'simple-timepicker/Gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simple-timepicker/dist/simple-timepicker.js' {
  declare module.exports: $Exports<'simple-timepicker/dist/simple-timepicker'>;
}
declare module 'simple-timepicker/dist/simple-timepicker.min.js' {
  declare module.exports: $Exports<'simple-timepicker/dist/simple-timepicker.min'>;
}
declare module 'simple-timepicker/Gruntfile.js' {
  declare module.exports: $Exports<'simple-timepicker/Gruntfile'>;
}
declare module 'simple-timepicker/index' {
  declare module.exports: $Exports<'simple-timepicker'>;
}
declare module 'simple-timepicker/index.js' {
  declare module.exports: $Exports<'simple-timepicker'>;
}
