// flow-typed signature: cae26206c27b780d9a5bf73206d7d459
// flow-typed version: <<STUB>>/simple-configure_v0.1.6/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-configure'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-configure' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simple-configure/Gruntfile' {
  declare module.exports: any;
}

declare module 'simple-configure/lib/simple-configure/index' {
  declare module.exports: any;
}

declare module 'simple-configure/test/simple-configure/simple-configure-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simple-configure/Gruntfile.js' {
  declare module.exports: $Exports<'simple-configure/Gruntfile'>;
}
declare module 'simple-configure/lib/simple-configure/index.js' {
  declare module.exports: $Exports<'simple-configure/lib/simple-configure/index'>;
}
declare module 'simple-configure/test/simple-configure/simple-configure-test.js' {
  declare module.exports: $Exports<'simple-configure/test/simple-configure/simple-configure-test'>;
}
