// flow-typed signature: 02bab7519a29d7c196e2e8dda49bd5b6
// flow-typed version: <<STUB>>/tinygradient_v0.3.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tinygradient'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tinygradient' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tinygradient/Gruntfile' {
  declare module.exports: any;
}

declare module 'tinygradient/tests/basics' {
  declare module.exports: any;
}

declare module 'tinygradient/tinygradient' {
  declare module.exports: any;
}

declare module 'tinygradient/tinygradient.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tinygradient/Gruntfile.js' {
  declare module.exports: $Exports<'tinygradient/Gruntfile'>;
}
declare module 'tinygradient/tests/basics.js' {
  declare module.exports: $Exports<'tinygradient/tests/basics'>;
}
declare module 'tinygradient/tinygradient.js' {
  declare module.exports: $Exports<'tinygradient/tinygradient'>;
}
declare module 'tinygradient/tinygradient.min.js' {
  declare module.exports: $Exports<'tinygradient/tinygradient.min'>;
}
