// flow-typed signature: 338230e79c765d75936a96ba3bc4a359
// flow-typed version: <<STUB>>/winston-config_v0.5.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston-config/Gruntfile' {
  declare module.exports: any;
}

declare module 'winston-config/lib/winston-config' {
  declare module.exports: any;
}

declare module 'winston-config/test/winston_config_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston-config/Gruntfile.js' {
  declare module.exports: $Exports<'winston-config/Gruntfile'>;
}
declare module 'winston-config/lib/winston-config.js' {
  declare module.exports: $Exports<'winston-config/lib/winston-config'>;
}
declare module 'winston-config/test/winston_config_test.js' {
  declare module.exports: $Exports<'winston-config/test/winston_config_test'>;
}
